Address what to delete when there is duplicates
AY2425S1-CS2103-F09-1/tp pull request #186
Opened 2024-11-02 14:42 UTC by cth06-Github

The placeholder code is meant to be replaced by the code in PR regarding main window UI.

2024-11-03 10:32 UTC, somethingfishyfishy requested changes

2024-11-03 10:32 UTC, somethingfishyfishy commented on src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
> +        }
After this, if we are going with version 2. We can try:


```
if (!preamble.isEmpty()) {
    throw new ParseException("unexpected arguments detected")
}
```

2024-11-03 10:32 UTC, somethingfishyfishy commented on src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
> +            throw new ParseException(MESSAGE_CONTACT_NOT_IN_ADDRESS_BOOK);
This is not the correct message. Original message is responding to "delete n/James&", where name specified is invalid.

Message_contact_not_in_address_book is only happens during execution when targetIndex is not found.

2024-11-06 17:02 UTC, wuzengfu approved these changes

2024-11-07 13:33 UTC, closed without merging